// This is a generated file, do not edit!
// Generated by P.swift, see https://github.com/mac-cain13/R.swift

import Foundation

class P:NSObject {
  class Index:NSObject {
    var data: Data?
    var description_p: String?
    var rs_status: String?
    
    class Query:NSObject {
      var count: String?
      var created: String?
      var lang: String?
      var results: Results?
      
      class Cases:NSObject {
        var comments: String?
        var image: String?
        var name: String?
        var nid: String?
        var title: String?
        var views: String?
      }
      
      class Doctors:NSObject {
        var avatar: String?
        var hname1: String?
        var hname2: String?
        var name: String?
        var tags:[Tags]?
        var title: String? 
        var uid: String?
        
        class Channel:NSObject {
          var item: Item?
          
          class Item:NSObject {
            var condition: Condition?
            
            class Condition:NSObject {
              var text: String?
            }
          }
        }
      }
    }
  }
}