// This is a generated file, do not edit!
// Generated by P.swift, see https://github.com/mac-cain13/R.swift

import Foundation

class P:NSObject {
  class Weather:NSObject {
    var query: Query?
    
    class Query:NSObject {
      var count: String?
      var created: String?
      var lang: String?
      var results: Results?
      
      class Results:NSObject {
        var channel: Channel?
        
        class Channel:NSObject {
          var item: Item?
          
          class Item:NSObject {
            var condition: Condition?
            
            class Condition:NSObject {
              var text: String?
            }
          }
        }
      }
    }
  }
}